---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/users":
    parameters:
    - name: email
      in: path
      description: email
      required: true
      schema:
        type: string
    - name: first_name
      in: path
      description: first_name
      required: true
      schema:
        type: string
    - name: last_name
      in: path
      description: last_name
      required: true
      schema:
        type: string
    - name: avatar
      in: path
      description: avatar
      required: true
      schema:
        type: string
    get:
      summary: list users
      responses:
        '200':
          description: successful
    post:
      summary: create user
      responses:
        '200':
          description: successful
  "/api/v1/users/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show user
      responses:
        '200':
          description: successful
    patch:
      summary: update user
      responses:
        '200':
          description: successful
    put:
      summary: update user
      responses:
        '200':
          description: successful
    delete:
      summary: delete user
      responses:
        '200':
          description: successful
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
